//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHQTCSDL_QLBH.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CTHD> CTHDs { get; set; }
        public virtual DbSet<CTPN> CTPNs { get; set; }
        public virtual DbSet<KHACHHANG> KHACHHANGs { get; set; }
        public virtual DbSet<LOAISANPHAM> LOAISANPHAMs { get; set; }
        public virtual DbSet<NHACUNGCAP> NHACUNGCAPs { get; set; }
        public virtual DbSet<NHANVIEN> NHANVIENs { get; set; }
        public virtual DbSet<PHIEUNHAP> PHIEUNHAPs { get; set; }
        public virtual DbSet<QUANTRI> QUANTRIs { get; set; }
        public virtual DbSet<SANPHAM> SANPHAMs { get; set; }
        public virtual DbSet<VIEW_DANHSACHHOADON> VIEW_DANHSACHHOADON { get; set; }
        public virtual DbSet<VIEW_DANHSACHPHIEUNHAP> VIEW_DANHSACHPHIEUNHAP { get; set; }
        public virtual DbSet<VIEW_DANHSACHSANPHAM> VIEW_DANHSACHSANPHAM { get; set; }
        public virtual DbSet<VIEW_HOATDONGCUANV> VIEW_HOATDONGCUANV { get; set; }
        public virtual DbSet<VIEW_LAIXUATCUASANPHAM> VIEW_LAIXUATCUASANPHAM { get; set; }
        public virtual DbSet<VIEW_DS_KHACHHANG> VIEW_DS_KHACHHANG { get; set; }
        public virtual DbSet<HOADON> HOADONs { get; set; }
    
        public virtual int SP_LAYSPBANDUOCNHIEUNHAT(Nullable<decimal> x)
        {
            var xParameter = x.HasValue ?
                new ObjectParameter("X", x) :
                new ObjectParameter("X", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LAYSPBANDUOCNHIEUNHAT", xParameter);
        }
    
        public virtual int UPDATE_CTHD_DONGIA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_CTHD_DONGIA");
        }
    
        public virtual int UPDATE_HOADON_TONGTG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("UPDATE_HOADON_TONGTG");
        }
    
        public virtual int SP_CAPNHATSANPHAM(string v_MASP, string v_TENSP, Nullable<decimal> v_SOLUONG, string v_DONVITINH, Nullable<decimal> v_DONGIA, string v_LOAISP)
        {
            var v_MASPParameter = v_MASP != null ?
                new ObjectParameter("V_MASP", v_MASP) :
                new ObjectParameter("V_MASP", typeof(string));
    
            var v_TENSPParameter = v_TENSP != null ?
                new ObjectParameter("V_TENSP", v_TENSP) :
                new ObjectParameter("V_TENSP", typeof(string));
    
            var v_SOLUONGParameter = v_SOLUONG.HasValue ?
                new ObjectParameter("V_SOLUONG", v_SOLUONG) :
                new ObjectParameter("V_SOLUONG", typeof(decimal));
    
            var v_DONVITINHParameter = v_DONVITINH != null ?
                new ObjectParameter("V_DONVITINH", v_DONVITINH) :
                new ObjectParameter("V_DONVITINH", typeof(string));
    
            var v_DONGIAParameter = v_DONGIA.HasValue ?
                new ObjectParameter("V_DONGIA", v_DONGIA) :
                new ObjectParameter("V_DONGIA", typeof(decimal));
    
            var v_LOAISPParameter = v_LOAISP != null ?
                new ObjectParameter("V_LOAISP", v_LOAISP) :
                new ObjectParameter("V_LOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATSANPHAM", v_MASPParameter, v_TENSPParameter, v_SOLUONGParameter, v_DONVITINHParameter, v_DONGIAParameter, v_LOAISPParameter);
        }
    
        public virtual int SP_THEMSANPHAM(string v_TENSP, Nullable<decimal> v_SOLUONG, string v_DONVITINH, Nullable<decimal> v_DONGIA, string v_LOAISP)
        {
            var v_TENSPParameter = v_TENSP != null ?
                new ObjectParameter("V_TENSP", v_TENSP) :
                new ObjectParameter("V_TENSP", typeof(string));
    
            var v_SOLUONGParameter = v_SOLUONG.HasValue ?
                new ObjectParameter("V_SOLUONG", v_SOLUONG) :
                new ObjectParameter("V_SOLUONG", typeof(decimal));
    
            var v_DONVITINHParameter = v_DONVITINH != null ?
                new ObjectParameter("V_DONVITINH", v_DONVITINH) :
                new ObjectParameter("V_DONVITINH", typeof(string));
    
            var v_DONGIAParameter = v_DONGIA.HasValue ?
                new ObjectParameter("V_DONGIA", v_DONGIA) :
                new ObjectParameter("V_DONGIA", typeof(decimal));
    
            var v_LOAISPParameter = v_LOAISP != null ?
                new ObjectParameter("V_LOAISP", v_LOAISP) :
                new ObjectParameter("V_LOAISP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMSANPHAM", v_TENSPParameter, v_SOLUONGParameter, v_DONVITINHParameter, v_DONGIAParameter, v_LOAISPParameter);
        }
    
        public virtual int SP_TINHLAIXUATCUASANPHAM()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_TINHLAIXUATCUASANPHAM");
        }
    
        public virtual int SP_UPDATEDONGIACTHD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATEDONGIACTHD");
        }
    
        public virtual int SP_UPDATETONGTGHOADON()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_UPDATETONGTGHOADON");
        }
    
        public virtual int SP_XOASANPHAM(string v_MASP)
        {
            var v_MASPParameter = v_MASP != null ?
                new ObjectParameter("V_MASP", v_MASP) :
                new ObjectParameter("V_MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOASANPHAM", v_MASPParameter);
        }
    
        public virtual int SP_CAPNHATCTHD(string v_SOHD, string v_MASP, Nullable<decimal> v_SOLUONG_MOI)
        {
            var v_SOHDParameter = v_SOHD != null ?
                new ObjectParameter("V_SOHD", v_SOHD) :
                new ObjectParameter("V_SOHD", typeof(string));
    
            var v_MASPParameter = v_MASP != null ?
                new ObjectParameter("V_MASP", v_MASP) :
                new ObjectParameter("V_MASP", typeof(string));
    
            var v_SOLUONG_MOIParameter = v_SOLUONG_MOI.HasValue ?
                new ObjectParameter("V_SOLUONG_MOI", v_SOLUONG_MOI) :
                new ObjectParameter("V_SOLUONG_MOI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATCTHD", v_SOHDParameter, v_MASPParameter, v_SOLUONG_MOIParameter);
        }
    
        public virtual int SP_CAPNHATCTPN(string v_MAPN, string v_MASP, Nullable<decimal> v_SOLUONG_MOI)
        {
            var v_MAPNParameter = v_MAPN != null ?
                new ObjectParameter("V_MAPN", v_MAPN) :
                new ObjectParameter("V_MAPN", typeof(string));
    
            var v_MASPParameter = v_MASP != null ?
                new ObjectParameter("V_MASP", v_MASP) :
                new ObjectParameter("V_MASP", typeof(string));
    
            var v_SOLUONG_MOIParameter = v_SOLUONG_MOI.HasValue ?
                new ObjectParameter("V_SOLUONG_MOI", v_SOLUONG_MOI) :
                new ObjectParameter("V_SOLUONG_MOI", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATCTPN", v_MAPNParameter, v_MASPParameter, v_SOLUONG_MOIParameter);
        }
    
        public virtual int SP_CAPNHATHOADON(string v_SOHD, Nullable<System.DateTime> v_NGAY, string v_MAKH, string v_MANV, Nullable<decimal> v_TONGTG)
        {
            var v_SOHDParameter = v_SOHD != null ?
                new ObjectParameter("V_SOHD", v_SOHD) :
                new ObjectParameter("V_SOHD", typeof(string));
    
            var v_NGAYParameter = v_NGAY.HasValue ?
                new ObjectParameter("V_NGAY", v_NGAY) :
                new ObjectParameter("V_NGAY", typeof(System.DateTime));
    
            var v_MAKHParameter = v_MAKH != null ?
                new ObjectParameter("V_MAKH", v_MAKH) :
                new ObjectParameter("V_MAKH", typeof(string));
    
            var v_MANVParameter = v_MANV != null ?
                new ObjectParameter("V_MANV", v_MANV) :
                new ObjectParameter("V_MANV", typeof(string));
    
            var v_TONGTGParameter = v_TONGTG.HasValue ?
                new ObjectParameter("V_TONGTG", v_TONGTG) :
                new ObjectParameter("V_TONGTG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATHOADON", v_SOHDParameter, v_NGAYParameter, v_MAKHParameter, v_MANVParameter, v_TONGTGParameter);
        }
    
        public virtual int SP_CAPNHATLOAISANPHAM(string v_MALOAI, string v_TENLOAI)
        {
            var v_MALOAIParameter = v_MALOAI != null ?
                new ObjectParameter("V_MALOAI", v_MALOAI) :
                new ObjectParameter("V_MALOAI", typeof(string));
    
            var v_TENLOAIParameter = v_TENLOAI != null ?
                new ObjectParameter("V_TENLOAI", v_TENLOAI) :
                new ObjectParameter("V_TENLOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATLOAISANPHAM", v_MALOAIParameter, v_TENLOAIParameter);
        }
    
        public virtual int SP_CAPNHATPHIEUNHAP(string v_MAPN, Nullable<System.DateTime> v_NGAYNHAP, string v_MANCC, string v_MANV)
        {
            var v_MAPNParameter = v_MAPN != null ?
                new ObjectParameter("V_MAPN", v_MAPN) :
                new ObjectParameter("V_MAPN", typeof(string));
    
            var v_NGAYNHAPParameter = v_NGAYNHAP.HasValue ?
                new ObjectParameter("V_NGAYNHAP", v_NGAYNHAP) :
                new ObjectParameter("V_NGAYNHAP", typeof(System.DateTime));
    
            var v_MANCCParameter = v_MANCC != null ?
                new ObjectParameter("V_MANCC", v_MANCC) :
                new ObjectParameter("V_MANCC", typeof(string));
    
            var v_MANVParameter = v_MANV != null ?
                new ObjectParameter("V_MANV", v_MANV) :
                new ObjectParameter("V_MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHATPHIEUNHAP", v_MAPNParameter, v_NGAYNHAPParameter, v_MANCCParameter, v_MANVParameter);
        }
    
        public virtual int SP_CAPNHAT_DOANHSO_KHACHHANG()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_CAPNHAT_DOANHSO_KHACHHANG");
        }
    
        public virtual int SP_THEMCTHD(string v_SOHD, string v_MASP, Nullable<decimal> v_SOLUONG)
        {
            var v_SOHDParameter = v_SOHD != null ?
                new ObjectParameter("V_SOHD", v_SOHD) :
                new ObjectParameter("V_SOHD", typeof(string));
    
            var v_MASPParameter = v_MASP != null ?
                new ObjectParameter("V_MASP", v_MASP) :
                new ObjectParameter("V_MASP", typeof(string));
    
            var v_SOLUONGParameter = v_SOLUONG.HasValue ?
                new ObjectParameter("V_SOLUONG", v_SOLUONG) :
                new ObjectParameter("V_SOLUONG", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMCTHD", v_SOHDParameter, v_MASPParameter, v_SOLUONGParameter);
        }
    
        public virtual int SP_THEMCTPN(string v_MAPN, string v_MASP, Nullable<decimal> v_SLNHAP, Nullable<decimal> v_DONGIANHAP)
        {
            var v_MAPNParameter = v_MAPN != null ?
                new ObjectParameter("V_MAPN", v_MAPN) :
                new ObjectParameter("V_MAPN", typeof(string));
    
            var v_MASPParameter = v_MASP != null ?
                new ObjectParameter("V_MASP", v_MASP) :
                new ObjectParameter("V_MASP", typeof(string));
    
            var v_SLNHAPParameter = v_SLNHAP.HasValue ?
                new ObjectParameter("V_SLNHAP", v_SLNHAP) :
                new ObjectParameter("V_SLNHAP", typeof(decimal));
    
            var v_DONGIANHAPParameter = v_DONGIANHAP.HasValue ?
                new ObjectParameter("V_DONGIANHAP", v_DONGIANHAP) :
                new ObjectParameter("V_DONGIANHAP", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMCTPN", v_MAPNParameter, v_MASPParameter, v_SLNHAPParameter, v_DONGIANHAPParameter);
        }
    
        public virtual int SP_THEMHOADON(string v_MAKH, string v_MANV)
        {
            var v_MAKHParameter = v_MAKH != null ?
                new ObjectParameter("V_MAKH", v_MAKH) :
                new ObjectParameter("V_MAKH", typeof(string));
    
            var v_MANVParameter = v_MANV != null ?
                new ObjectParameter("V_MANV", v_MANV) :
                new ObjectParameter("V_MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMHOADON", v_MAKHParameter, v_MANVParameter);
        }
    
        public virtual int SP_THEMLOAISANPHAM(string v_MALOAI, string v_TENLOAI)
        {
            var v_MALOAIParameter = v_MALOAI != null ?
                new ObjectParameter("V_MALOAI", v_MALOAI) :
                new ObjectParameter("V_MALOAI", typeof(string));
    
            var v_TENLOAIParameter = v_TENLOAI != null ?
                new ObjectParameter("V_TENLOAI", v_TENLOAI) :
                new ObjectParameter("V_TENLOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMLOAISANPHAM", v_MALOAIParameter, v_TENLOAIParameter);
        }
    
        public virtual int SP_THEMPHIEUNHAP(string v_MANCC, string v_MANV)
        {
            var v_MANCCParameter = v_MANCC != null ?
                new ObjectParameter("V_MANCC", v_MANCC) :
                new ObjectParameter("V_MANCC", typeof(string));
    
            var v_MANVParameter = v_MANV != null ?
                new ObjectParameter("V_MANV", v_MANV) :
                new ObjectParameter("V_MANV", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_THEMPHIEUNHAP", v_MANCCParameter, v_MANVParameter);
        }
    
        public virtual int SP_XOACTHD(string v_SOHD, string v_MASP)
        {
            var v_SOHDParameter = v_SOHD != null ?
                new ObjectParameter("V_SOHD", v_SOHD) :
                new ObjectParameter("V_SOHD", typeof(string));
    
            var v_MASPParameter = v_MASP != null ?
                new ObjectParameter("V_MASP", v_MASP) :
                new ObjectParameter("V_MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOACTHD", v_SOHDParameter, v_MASPParameter);
        }
    
        public virtual int SP_XOACTPN(string v_MAPN, string v_MASP)
        {
            var v_MAPNParameter = v_MAPN != null ?
                new ObjectParameter("V_MAPN", v_MAPN) :
                new ObjectParameter("V_MAPN", typeof(string));
    
            var v_MASPParameter = v_MASP != null ?
                new ObjectParameter("V_MASP", v_MASP) :
                new ObjectParameter("V_MASP", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOACTPN", v_MAPNParameter, v_MASPParameter);
        }
    
        public virtual int SP_XOAHOADON(string v_SOHD)
        {
            var v_SOHDParameter = v_SOHD != null ?
                new ObjectParameter("V_SOHD", v_SOHD) :
                new ObjectParameter("V_SOHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOAHOADON", v_SOHDParameter);
        }
    
        public virtual int SP_XOALOAISANPHAM(string v_MALOAI)
        {
            var v_MALOAIParameter = v_MALOAI != null ?
                new ObjectParameter("V_MALOAI", v_MALOAI) :
                new ObjectParameter("V_MALOAI", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOALOAISANPHAM", v_MALOAIParameter);
        }
    
        public virtual int SP_XOAPHIEUNHAP(string v_MAPN)
        {
            var v_MAPNParameter = v_MAPN != null ?
                new ObjectParameter("V_MAPN", v_MAPN) :
                new ObjectParameter("V_MAPN", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_XOAPHIEUNHAP", v_MAPNParameter);
        }
    
        public virtual int SP_LAYDANHSACH_CTHD(string v_SOHD)
        {
            var v_SOHDParameter = v_SOHD != null ?
                new ObjectParameter("V_SOHD", v_SOHD) :
                new ObjectParameter("V_SOHD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_LAYDANHSACH_CTHD", v_SOHDParameter);
        }
    
        public virtual int SP_MAHOAMATKHAU(string p_PASSWORD, ObjectParameter p_HASHEDPASSWORD)
        {
            var p_PASSWORDParameter = p_PASSWORD != null ?
                new ObjectParameter("P_PASSWORD", p_PASSWORD) :
                new ObjectParameter("P_PASSWORD", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_MAHOAMATKHAU", p_PASSWORDParameter, p_HASHEDPASSWORD);
        }
    }
}
