//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHQTCSDL_QLBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_HOATDONGCUANV
    {
        public string MANV { get; set; }
        public string HOTEN { get; set; }
        public string GIOITINH { get; set; }
        public string SDT { get; set; }
        public string DIACHI { get; set; }
        public Nullable<decimal> LUONG { get; set; }
        public Nullable<decimal> SOHDDALAP { get; set; }
        public Nullable<decimal> SOPHIEUDALAP { get; set; }
        public Nullable<decimal> LOINHUAN { get; set; }
    }
}
