//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHQTCSDL_QLBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DANHSACHSANPHAM
    {
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> SLNHAP { get; set; }
        public Nullable<decimal> SLTON { get; set; }
        public Nullable<decimal> SLBAN { get; set; }
        public string DVT { get; set; }
        public string LOAISP { get; set; }
        public Nullable<decimal> DONGIA { get; set; }
    }
}
