//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHQTCSDL_QLBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DANHSACHPHIEUNHAP
    {
        public string MAPN { get; set; }
        public Nullable<System.DateTime> NGAYNHAP { get; set; }
        public string TENNCC { get; set; }
        public string TENNV { get; set; }
        public Nullable<decimal> TONGTIENNHAP { get; set; }
    }
}
