//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHQTCSDL_QLBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_DS_KHACHHANG
    {
        public string MAKH { get; set; }
        public string HOTEN { get; set; }
        public string DIACHI { get; set; }
        public string SODT { get; set; }
        public string EMAIL { get; set; }
        public Nullable<decimal> SOHDSOHUU { get; set; }
        public Nullable<decimal> DOANHSO { get; set; }
        public Nullable<decimal> DIEMTICHLUY { get; set; }
    }
}
