//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CHQTCSDL_QLBH.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VIEW_LAIXUATCUASANPHAM
    {
        public string MASP { get; set; }
        public string TENSP { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
        public Nullable<decimal> LAIXUAT { get; set; }
    }
}
